---
- name: "install npi"
  shell: bash -c "$(curl -sSL {{npi_download}})"
    creates="{{npi_prefix}}/npi"
  environment:
    LICENSE_KEY: '{{new_relic_license_key}}'
    PREFIX: "{{npi_prefix}}"
    UNATTENDED: 'true'
# Default binary expects you to be running from the npi_prefix
- name: "add npi binary"
  template:
    src=npi.j2
    dest={{npi_bin}}
    mode=0755
- name: "install java"
  apt: name="{{npi_java_package}}" state=present
- name: "fetch npi plugins"
  shell: npi fetch "{{item}}" -y
    creates="{{npi_prefix}}/plugins/{{item.key}}"
  with_dict: npi_plugins
- name: "get plugin location"
  shell: "npi where {{item.key}}"
  register: npi_plugin_locations
  with_dict: npi_plugins
  changed_when: no
- name: "add plugin services"
  template:
    src=npi-plugin-upstart.conf.j2
    dest=/etc/init/{{item.key}}.conf
  with_dict: npi_plugins
- name: "add plugin configs"
  template:
    src="{{npi_plugins[item.item].template}}"
    dest="{{item.stdout}}/config/plugin.json"
  when: npi_plugins[item.item].template is defined
  with_items: npi_plugin_locations.results
- name: "restart plugin services"
  service: name="{{item.key}}" state=restarted
  with_dict: npi_plugins
